# Generated by Django 4.2.9 on 2024-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
