# Generated by Django 4.2.9 on 2024-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_user_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
